### ISSUE TITLE
Reference Model Browser ("Mora-Doc") needs to be valid XML

### ISSUE THREAD

**Issue by cmoesel** [standardhealth/ballot#12]
See: https://chat.fhir.org/#narrow/stream/IG.20creation/topic/Including.20non-XHTML.20pages

**Comment by markkramerus** [comment]
Abhijay, please run an html validator on the html and make sure we have closed our brackets, dotted our eyes, and crossed our toes.

**Comment by Abhijay** [comment]
Update: the xhtml files are now schema-valid. There are still many 'broken' links that may or may not need to be fixed, determination still pending.

xhtml files fixed here: https://github.com/standardhealth/shr-json-javadoc/pull/4

**Comment by markkramerus** [comment]
Is this ready to close?

**Comment by cmoesel** [comment]
Depends on how you want to look at it.  Files are XHTML now, but IG Publisher is reporting lots of broken links.  That's what @Abhijay is looking at now.

So we can close it and open a new issue to fix the links, or we can keep it open until the links are fixed.

**Comment by Abhijay** [comment]
The pages are valid in both ways as of: https://github.com/standardhealth/shr-json-javadoc/releases/tag/v1.3.1

Will close this issue after it is merged into the cli.
