### ISSUE TITLE
Ugly column spacing due to lack of spaces between class names 

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/ballot#13]
See http://build.fhir.org/ig/HL7/us-breastcancer/StructureDefinition-oncology-HER2byISH.html
The Snapshot tab, the far right column (Description & Constraints) is really squished. 
The reason is the length of this line: 

Reference(CarePlanDeviceRequestImmunizationRecommendationMedicationRequestNutritionOrderProcedureRequestReferralRequest)

This isn't our code, unfortunately. Can someone (Chris) pass this bug onto the publisher tools maintainer (Grahame?)
If there some way to get a space between the class names, that would do it.

**Comment by cmoesel** [comment]
This is more than a UI bug, as it seems that the JSON download of the artifact also strips out the reference targets from that choice.  There is a Zulip thread tracking this:
https://chat.fhir.org/#narrow/stream/IG.20creation/topic/Bad.20Choice.20Rendering.20.2B.20JSON.20mangling

**Comment by cmoesel** [comment]
Thankfully, this is fixed!
