### ISSUE TITLE
Missing valueQuantity in component 

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/ballot#14]
See the IG page for HER2ReceptorStatusISH: http://build.fhir.org/ig/HL7/us-breastcancer/StructureDefinition-oncology-HER2byISH.html) 

In the profile, valueQuantity is missing from the profile in two of the components (AverageHER2SignalsPerCell and AverageCEP17SignalsPerCell) 

Note: this is the same bug as[ HIGH PRIORITY: Observation Components in profile are missing valueQuantity #75](https://github.com/standardhealth/shr-cli/issues/75) in shr-cli, but I copied it here because it needs to be fixed for the ballot.

That bug has a picture :)

**Comment by cmoesel** [comment]
Seems like when we apply a constraint on the Quantity, it shows up.  But if we don't... gone!  Will debug it.

**Comment by cmoesel** [comment]
Fixed.  See the standardhealth/shr-cli#75 for the screenshot.
