### ISSUE TITLE
http://loinc.org is not a value set

### ISSUE THREAD

**Issue by cmoesel** [standardhealth/ballot#17]
The `cimi.txt` definitions contain the following:
```
Element:		FindingMethod
Concept:		TBD
Description:	"The technique used to create the finding, for example, the specific imaging technical, lab test code, or assessment vehicle. In CIMI Version 0.0.4, this attribute is called 'method'."
Value:			CodeableConcept should be from http://loinc.org
```

This is not valid, as http://loinc.org is not a value set.  As a result, the FHIR IG Publisher emits a warning.  If the intent is to cover all codes in LOINC, consider: http://hl7.org/fhir/ValueSet/observation-codes

See: https://github.com/standardhealth/shr_spec/blob/may-2018-ballot/spec/cimi.txt#L170

**Comment by markkramerus** [comment]
Good catch, thanks. Simple change.

**Comment by cmoesel** [comment]
Can you push this to the `may_2018_ballot` branch?  I'd like to stop seeing that error -- as it's one of the only ones left!
