### ISSUE TITLE
Add narrative intro to extensions

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/ballot#2]

**Comment by markkramerus** [comment]
What does this means? We aren't going to write custom, individualized descriptions of each extension. Is that what you mean?

**Comment by rutemartins** [comment]
No - I mean an intro on the extensions page that explains briefly what the body of content is about.

**Comment by cmoesel** [comment]
@rutemartins -- I'm still not tracking.  Do you mean you want some narrative text on this page?
http://build.fhir.org/ig/HL7/us-breastcancer/extensions.html

If so, can you propose some text?

**Comment by rutemartins** [comment]
Mark addressed this in the landing page. No need to duplicate.
