### ISSUE TITLE
Logical Models don't support slicing -- how to represent "includes code" type?

### ISSUE THREAD

**Issue by cmoesel** [standardhealth/ballot#21]
Logical models do not support slicing (see [thread1](https://chat.fhir.org/#narrow/stream/IG.20creation/topic/sdf-1.3A.20Element.20paths.20must.20be.20unique.20unless.20the.20structure.20is) and [thread2](https://chat.fhir.org/#narrow/stream/implementers/topic/Logical.20Model.20and.20slicing.20for.20terminology)).  We can get around this in most cases, but the one remaining case is "includes code" constraints, and it manifests itself in `BreastCancerPresenceStatement`.

`BreastCancerPresenceStatement` specifies:
```
Category includes #disease
```

`Category` is `0..*`, so we normally would do this by _slicing_ `Category` and saying one must be `#disease`.  Since slicing is not allowed, however, we need an alternate approach when exporting to logical models.

One approach would be to just allow one `category` (the fixed one) and don't allow any others to be added:
```
category             1..1      Coding      #disease
```

Another approach, if we want to allow other codes as well, would be to have a high-level `category` section with _n_ `1..1` `fixed` sub-elements and one `0..*` `rest` element.
```
category             1..1
    - fixed          1..1      Coding      #disease
    - rest           0..*      Coding
```

Any preference?  Keep in mind that whatever we choose should be how we want it to be in all cases (not just this one specific `BreastCancerPresenceStatement.Categor` use case).

**Comment by cmoesel** [comment]
@markkramerus -- I need you to weigh in on this.

**Comment by markkramerus** [comment]
Two options:
1) Include this in a "Known Limitations" documentation section and do nothing else (since the ballot materials must be finalized by Friday, preferably Thursday since I'll be driving to Rochester in the car most of the day on Friday)
2)  My preference, if we decide to fix it once and for good would be to respect the upper cardinality, and allow multiple Categories -- as in the second option.

**Comment by cmoesel** [comment]
I don't know if `1` ("known limitation") is an option.  It depends on how serious the FHIR team is about IG's having _no errors_.  As it is now, this is a spec violation reported by the IG publisher.

**Comment by cmoesel** [comment]
That 2nd approach doesn't sit well with me.  On further thought, I think we can use a `constraint` (a.k.a. `invariant`) to indicate that the first code must #disease.  I'll see if I can figure out the right expression to say that.

The upside is that it doesn't affect the structure of the logical model.  The downside is that the fixed code requirement isn't as easy to notice.

**Comment by cmoesel** [comment]
Fixed via an invariant:
![image](https://user-images.githubusercontent.com/2278253/38009613-2d862ea2-3223-11e8-870e-e9b3d0712739.png)
