### ISSUE TITLE
Need help with Slicing ASAP

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/ballot#22]
Just did a commit to may-2018-ballot (6:35 am on 3/27/2018). I realized I wasn't mapping BreastSpecimen correctly, and the ColdIschemiaTime needs to be a slide in the Specimen.processing array. I can't quite figure out how to accomplish it, so I need help on the correct grammar. My intent will be clear from the following:

BreastSpecimen maps to Specimen:
	ColdIschemiaTime maps to processing (slice on = coding.code)
//	ColdIschemiaTime maps to processing.time[x]
//	ColdIschemiaTime._Concept maps to processing.procedure
//	constrain processing.additive to 0..0
//	constrain description to "Cold Ischemia Time"

**Comment by cmoesel** [comment]
OK.  I'll take a look at this.

One thing I see right away: the proper grammar for _fixing_ values is `fix x to y`, so your last line needs to be:
```
fix description to "Cold Ischemia Time"
```
BUT... there is currently a further limitation in the grammar when fixing strings; it doesn't support strings that contain any spaces.  So even the fixed rule above will cause problems since `"Cold Ischemia Time"` contains spaces.

**Comment by cmoesel** [comment]
OK.  This is what you need:
```
BreastSpecimen maps to Specimen:
	ColdIschemiaTime maps to processing (slice on = procedure)
	ColdIschemiaTime.TimePeriod maps to processing.time[x]
	ColdIschemiaTime._Concept maps to processing.procedure
	constrain processing.additive to 0..0
	fix processing.description to "ColdIschemiaTime"
```

A few notes regarding the fixes:
* The original mapping said to slice on `code.coding`, but `processing` doesn't have a `code` property.  We really need to slice on `procedure`.
* The original mapping mapped `ColdIschemiaTime` twice (once to `processing` and once to `processing.time[x]`).  The second time, we're really trying to map the _value_ (hence `ColdIschemiaTime.TimePeriod`).
* As noted above, when fixing a value (as opposed to constraining a cardinality), we need to use the `fix` keyword.
* The original mapping was trying to fix `description`.  It was missing the `processing.` prefix.
* As noted above, we're currently limited to fixing strings with no spaces.  Removing this limitation will require a grammar change.  I may be able to look into it if it is a big deal.

**Comment by cmoesel** [comment]
Better?

![image](https://user-images.githubusercontent.com/2278253/37970972-cf4f5ee2-31a2-11e8-86de-09c9bd9a4bfd.png)

**Comment by cmoesel** [comment]
On second thought, do you *really* want to fix the `description`?  You're indicating that when people send this data, they must include a `description` and it must be that specific value.  I think this may be too rigid -- and it doesn't allow people to provide more detail in the description.

It seems to me that fixing the code to LOINC 44778-9 should be enough to enforce what it is, and the documentation is already labeling the slice as `ColdIschemiaTime`, so it's clear to viewers what this slice represents.

**Comment by markkramerus** [comment]
excellent. Thanks.
