### ISSUE TITLE
Unlimited Codings allowed for `<Field> is <code>` CIMPL in IG

### ISSUE THREAD

**Issue by okeefm** [standardhealth/ballot#23]
If an element is defined with a `<Field> is <code>` definition, such as `TopicCode is LNC#76544-6`, one would expect that the `Coding` element that maps to would allow `1..1` of these `Coding`s. Instead, you are allowed to have `0..*` of these same `Coding` elements, all fixed to the same code.

Element that exhibits the issue: http://build.fhir.org/ig/HL7/us-breastcancer/StructureDefinition-oncology-ProsignaRecurrenceScore.html (look under Code)

Screenshot: 
<img width="709" alt="screen shot 2018-03-27 at 10 07 54 am" src="https://user-images.githubusercontent.com/49001/37973748-32c30dec-31a9-11e8-909b-05f80729eb85.png">

CIMPL for this element: 
    EntryElement:	ProsignaRecurrenceScore
    Based on:		SimplifiedLaboratoryTestResultRecorded
    Concept:		LNC#76544-6
    Description:	"Breast cancer genomic signature assay for 10-year risk of distant recurrence score calculated by Prosigna.

    The Prosigna Score is reported on a 0 -100 scale (referred to as ROR Score or Risk of Recurrence Score in the literature), which is correlated with the probability of distant recurrence at ten years for post-menopausal women with hormone receptorpositive, early stage breast cancer."
    Value: 			Quantity with units UCUM#1
				TopicCode is LNC#76544-6
				Interpretation from RecurrenceRiskScoreInterpretationVS
				DiagnosticService is #pathology
				Specimen is type BreastSpecimen
    0..0			EvaluationComponent

**Comment by cmoesel** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/2278253/37978093-2f1ecc44-31b3-11e8-8067-83206f83f0d3.png)

**Comment by cmoesel** [comment]
Here's the differential view (matching your original screenshot)...
![image](https://user-images.githubusercontent.com/2278253/37978176-71df3000-31b3-11e8-8d53-9865983c4321.png)
