### ISSUE TITLE
Disappearing Concept code?

### ISSUE THREAD

**Issue by okeefm** [standardhealth/ballot#25]
When I look at an Element like `BreastCancerStage`, which includes `0..1 StageTimingPrefix`; the `Value` of that timing element gets mapped onto the `BreastCancerStage` element, but the `Concept` code defined in the timing element appears to disappear. Is this intentional?

Link: http://build.fhir.org/ig/HL7/us-breastcancer/StructureDefinition-oncology-BreastCancerStage.html (view `oncology-StageTimingPrefix-extension`)

CIMPL from the topic-context branch:

    EntryElement:	BreastCancerStage
    Based on:		EvaluationResultRecorded  // maps to FHIR Observation
    Concept:		LNC#21908-9
    Description:	"<description>"
    0..1			StageTimingPrefix
    (rest of element)

        Element:		StageTimingPrefix
	Concept:		SCT#260869008 "Timing of stage"
	Description:	"<description>"
	Value:			CodeableConcept	from StageTimingPrefixVS

Screenshot:
<img width="889" alt="screen shot 2018-03-28 at 7 38 07 am" src="https://user-images.githubusercontent.com/49001/38026672-01b65ef4-325b-11e8-8297-54876f9618f4.png">

The SNOMED code `260869008` appears in the `StageTimingPrefix` element's CIMPL, but not in the IG; this is the discrepancy I'm asking about here.

**Comment by cmoesel** [comment]
Yes, this is expected.  The `Concept` of a CIMPL element is definitional.  It provides an external reference to the semantic meaning of the element.  It only shows up in the FHIR profiles if it is explicitly mapped to something (which in this case, it is not).
