### ISSUE TITLE
Missing Display Name in component codings?

### ISSUE THREAD

**Issue by okeefm** [standardhealth/ballot#26]
When a `component` has a `Concept` with a code, system and display name, like `Concept: SCT#126926005 "M category"`, the `display` doesn't show up in the IG.

Link: http://build.fhir.org/ig/HL7/us-breastcancer/StructureDefinition-oncology-BreastCancerStage.html (any of the `BreastCancer<x>Classification` components exhibit this)

Example CIMPL:

Parent element:

    EntryElement:	BreastCancerStage
    Based on:		EvaluationResultRecorded  // maps to FHIR Observation
    (lines removed for brevity)
    includes 0..1 	BreastCancerDistantMetastasesClassification

Component element:

    Element:		BreastCancerDistantMetastasesClassification
    Concept:		SCT#126926005 "M category"	//RMB: was LNC#59522-3, which is specific to AJCC 7th edition
    Based on:		EvaluationComponent
    Description:	"The presence of distant metastases, based on criteria defined by the staging system being used."
    Value:			CodeableConcept
    0..0			ReferenceRange

Screenshot:
<img width="779" alt="screen shot 2018-03-28 at 8 20 12 am" src="https://user-images.githubusercontent.com/49001/38028501-171e8a04-3261-11e8-897b-f0876ac827db.png">

**Comment by cmoesel** [comment]
We can't fix the `display`, as that would be too rigid (incoming data shouldn't _have_ to match on display).  That said, we may be able to put the display in the description field for the `coding` or the `code`.  I'll look into it.

**Comment by okeefm** [comment]
That makes sense.

**Comment by cmoesel** [comment]
Fixed locally for profiles and logical models.

![image](https://user-images.githubusercontent.com/2278253/38052616-d7c911e6-329f-11e8-8d2d-46861cb14cbf.png)

**Comment by cmoesel** [comment]
Confirmed fixed in build.fhir.org.
