### ISSUE TITLE
Code in Element doesn't match display text

### ISSUE THREAD

**Issue by okeefm** [standardhealth/ballot#27]
The element `CompleteMembraneStainingPercent`'s `Concept` code doesn't match the display text given for that code.

The code is LOINC code [16112-5](https://s.details.loinc.org/LOINC/16112-5.html), which is "Estrogen receptor [interpretation] in tissue", while the display text is from LOINC code [85328-3](https://r.details.loinc.org/LOINC/85328-3.html),

Offending line in the CIMPL:
https://github.com/standardhealth/shr_spec/blob/may-2018-ballot-topic-context/spec/oncology.txt#L234

Element shows up here (the `display` doesn't, but if Chris fixes #26 it will): http://build.fhir.org/ig/HL7/us-breastcancer/StructureDefinition-oncology-HER2byIHC.html

**Comment by markkramerus** [comment]
Fixed in CIMPL source
