### ISSUE TITLE
Logical Model missing Constraint on Value

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/ballot#28]
See BreastCancerHistologicGrade: 

Profile -- looks correct
valueCodeableConcept  Binding: NottinghamCombinedGradeVS (required)

In Logical Model: No constraints on value

value[x] |   | 0..1 | http://hl7.org/fhir/us/breastcancer/StructureDefinition/shr-core-Quantity-model, Coding, string, boolean, http://hl7.org/fhir/us/breastcancer/StructureDefinition/shr-core-Range-model, http://hl7.org/fhir/us/breastcancer/StructureDefinition/shr-core-Ratio-model, time, dateTime, http://hl7.org/fhir/us/breastcancer/StructureDefinition/shr-core-TimePeriod-model

**Comment by cmoesel** [comment]
I'll check it out.

**Comment by cmoesel** [comment]
Good find, Mark.  I've fixed this locally and will push it out to the site after we have a few more fixes in.

![image](https://user-images.githubusercontent.com/2278253/38049581-9c6025b2-3296-11e8-8fc8-9c59bd6d7295.png)

You'll note that it's sliced here.  That's for the same reason as indicated in #30.  If you don't like it, the same fix applies (constraining the value to CodeableConcept in the CIMPL).

**Comment by cmoesel** [comment]
Confirmed fixed on build.fhir.org.
