### ISSUE TITLE
Tab Label in Reference Model Browser

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/ballot#32]
Should not say Java Platform SE 7

![capture](https://user-images.githubusercontent.com/492232/38041670-601b3a62-3280-11e8-95cd-65f903d8392a.JPG)

**Comment by Abhijay** [comment]
Re-opening an auto-closed commit.

Will close when build is on build.fhir.org and verified

**Comment by cmoesel** [comment]
Verified on build.fhir.org.
