### ISSUE TITLE
Double period in IG generation statement

### ISSUE THREAD

**Issue by okeefm** [standardhealth/ballot#34]
This sentence is at the top of all the profile/logical model pages:
`This logical model was published on Wed Mar 28 00:00:00 UTC 2018 as a draft by The HL7 Cancer Interoperability Group sponsored by Clinical Interoperability Council Work Group (CIC)..`

It has a double period at the end. Is this editable when we publish the IG?

Also, the time is not correct (unless you published this at exactly 8 PM last night). I assume this is also a limitation of the IG publisher?

**Comment by cmoesel** [comment]
This is because the `publisher` property in the config.json has a period at the end:
```
"publisher": "The HL7 Cancer Interoperability Group sponsored by Clinical Interoperability Council Work Group (CIC).",
```

That period really shouldn't be there.

https://github.com/standardhealth/shr_spec/blob/may-2018-ballot-topic-context/spec/config.json#L10

**Comment by markkramerus** [comment]
I wish all bugs were this simple to fix :)
