### ISSUE TITLE
"shr-" prefixes still exist in the IG

### ISSUE THREAD

**Issue by okeefm** [standardhealth/ballot#35]
URLs for types defined in this ballot still contain the `shr-` prefix:  http://build.fhir.org/ig/HL7/us-breastcancer/StructureDefinition-oncology-BreastCancerHistologicGrade-model-definitions.html contains several examples:

* http://build.fhir.org/ig/HL7/us-breastcancer/StructureDefinition-shr-core-Quantity-model.html
* http://build.fhir.org/ig/HL7/us-breastcancer/StructureDefinition-shr-core-Range-model.html
* http://build.fhir.org/ig/HL7/us-breastcancer/StructureDefinition-shr-core-Ratio-model.html
* http://build.fhir.org/ig/HL7/us-breastcancer/StructureDefinition-shr-core-TimePeriod-model.html
* http://build.fhir.org/ig/HL7/us-breastcancer/StructureDefinition-shr-core-Category-model.html

Others include:

* http://hl7.org/fhir/us/breastcancer/StructureDefinition/shr-core-Comparator-model
* http://hl7.org/fhir/us/breastcancer/StructureDefinition/shr-core-Units-model

Should these be prefixed with the `shr-` prefix? Or should that be removed in favor of something like `oncology-`, as has been done for other types?

Also, there are many types that still contain the `cimi-` prefix, such as http://build.fhir.org/ig/HL7/us-breastcancer/StructureDefinition-cimi-statement-Members-model.html . Should those prefixes be there as well?

**Comment by cmoesel** [comment]
Those prefixes reflect the namespaces from which the elements came.  I think they need to stay.

**Comment by okeefm** [comment]
If so, that's fine. I just wanted to ensure these don't need to go away as a result of the "debranding" I'm supposed to be doing.

**Comment by cmoesel** [comment]
Since @markkramerus asked you to do the debranding, feel free to run it by him.  But I'm not sure how we easily get around this one without instituting some special case code that would have to be turned _off_ when we generate an SHR IG.

**Comment by markkramerus** [comment]
It's minimized, but the datatypes are all shr types. So that's why you see it. Thanks for checking. Might as well have a little something in there with SHR :-)
