### ISSUE TITLE
Ballot name needs to be updated

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/ballot#36]
Official name is HL7 FHIR® Implementation Guide: Breast Cancer Data, Release 1 - US Realm

**Comment by cmoesel** [comment]
This needs to be updated in the config.json.  Currently it is set to:
```
"projectName": "Breast Cancer Interoperability",
```

https://github.com/standardhealth/shr_spec/blob/may-2018-ballot-topic-context/spec/config.json#L2

**Comment by markkramerus** [comment]
Fixed.
