### ISSUE TITLE
Note on broken URLs should be removed

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/ballot#37]
Remove "NOTE: Due to current limitations in the FHIR IG publishing tool, when a property's type is another logical model, that type is displayed as a canonical URL and is not linked to the corresponding logical model page. Future versions of the publishing tool are expected to address this." from logical models pages.

This is not expected to be a problem once the ballot is published.

**Comment by cmoesel** [comment]
Actually that note still applies.  It's referring to this:

![image](https://user-images.githubusercontent.com/2278253/38047554-efd0dd64-3290-11e8-824d-b1f62d6282d5.png)

That URL is long and unlinked.  Ideally it would just say `cimi-TopicCode-model` and be linked to the appropriate page.  That's not something that publishing is going to fix.

**Comment by rutemartins** [comment]
So which URLs are broken in the build that will be fixed with the publication?

**Comment by cmoesel** [comment]
Any that actually _link_ to a URL starting with http://hl7.org/fhir/us/breastcancer/.  Right now, I think that only happens for the value sets in the "Reference Model" documentation.  But @Abhijay is actually working on a separate fix for that so the links _always_ work (even prior to publication).
