### ISSUE TITLE
Profiles & Logical models in VS "References" Section appear to be duplicates of each other

### ISSUE THREAD

**Issue by okeefm** [standardhealth/ballot#38]
If a ValueSet is referenced in both the Profile and Logical Model for a given type, they both show up as only the type definition (for example, `BreastCancerPresenceStatement`). This makes it look like the reference has been duplicated, when in fact they are different references. Do we care about this? And if so, is it possible to change this, or is it hardcoded into the IG generator?

Example: http://build.fhir.org/ig/HL7/us-breastcancer/ValueSet-cimi-ConditionCategoryVS.html

<img width="430" alt="screen shot 2018-03-28 at 1 39 30 pm" src="https://user-images.githubusercontent.com/49001/38046514-def30c2c-328d-11e8-9737-fe18e3f5b41e.png">

**Comment by cmoesel** [comment]
Oh.  Interesting.  I don't know.  I can look.

**Comment by cmoesel** [comment]
Fixed locally.

![image](https://user-images.githubusercontent.com/2278253/38054616-80693696-32a5-11e8-86d8-b435f946f2f5.png)

**Comment by cmoesel** [comment]
This fix is now live on buid.fhir.org.  The value set referenced above no longer exists, but you can see it in other value sets like this one:
http://build.fhir.org/ig/HL7/us-breastcancer/ValueSet-oncology-NottinghamCombinedGradeVS.html
