### ISSUE TITLE
Diagnostic Service Valueset questions

### ISSUE THREAD

**Issue by okeefm** [standardhealth/ballot#39]
Where do the codes/definitions for the `DiagnosticServiceVS`, http://build.fhir.org/ig/HL7/us-breastcancer/ValueSet-cimi-statement-DiagnosticServiceVS.html, come from? I have a couple of questions:

* `Immunohaematology` should be spelled `Immunohematology` (without the ae) to align with `hematology` which is also in the valueset
* `Immunohematology` should not be capitalized, as all the other codes in this valueset are lower-case.
* `toxicology`'s definition should be expanded past just "drug testing", as toxicology can be used to test for any potential toxin in the blood, whether pharmaceutical in nature or otherwise.
* The definition for `parasitology` could be rewritten to be more concise and grammatically correct.

**Comment by markkramerus** [comment]
Good, glad you're getting down to a level of detail here. Done.
