### ISSUE TITLE
Base model is not fully CIMI compliant

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/ballot#4]
The class hierarchy builds classes by inheriting through StatementTopic, not ClinicalStatement. There were some bugs in the profiles when I tried using the full ClinicalStatement pattern. The profile generator was dying trying to map paths like MyClinicalStatement.MyTopic.MyAttribute . There is a branch, may-2018-ballot-topic-context that demonstrates the problem.

**Comment by cmoesel** [comment]
I've fixed this bug.  The SHR-CLI runs clean and the resulting guide looks good at first glance.  That said, "first glance" only lasted about 90 seconds, so you should review it further.  @markkramerus:  I'll send you more detail and a link to the generated guide via email.

**Comment by cmoesel** [comment]
@markkramerus - have you had time to review this well enough to determine if we can close the issue?

**Comment by markkramerus** [comment]
Just did. It's not fixed satisfactorily. CLI runs clean, but the profiles aren't right. Compare the profile pages for StructureDefinition-oncology-BreastCancerPresenceStatement.html generated from the may-2018-ballot-topic-context branch:
![capture](https://user-images.githubusercontent.com/492232/37799307-c1014928-2df5-11e8-99f3-124951028564.JPG)
versus the one generated with the may-2018-ballot branch:
![capture2](https://user-images.githubusercontent.com/492232/37799372-e7c5816e-2df5-11e8-8216-3219fa9e7b06.JPG)
The definitions are necessarily somewhat different, but they should result in the same profiles, or at least very similar. But the first has virtually nothing in it.

**Comment by cmoesel** [comment]
Hmmm... OK.  I'll have to look at that then.

**Comment by cmoesel** [comment]
![fixedbreastcancerpresencestatement](https://user-images.githubusercontent.com/2278253/37804518-04bfd106-2e0b-11e8-820b-c9e4ec07d9cc.png)

Better?

**Comment by markkramerus** [comment]
OK, we are going to switch to the topic-context branch as our "go to ballot" branch.
