### ISSUE TITLE
LateralityVS vs. LeftRightLateralityVS

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/ballot#40]
I changed the LeftRightLateralityVS in a previous commit to align with the FHIR Laterality vs. I realized there's a LateralityVS (apparently coming from CIMI) that uses NCI codes instead, and seems to be aligned with the "old" LeftRightLateralityVS. Do we give precedence to the CIMI definition or the FHIR definition? Also, why do we need the LateralityVS?

**Comment by cmoesel** [comment]
Mark removed the LeftRightLateralityVS in this commit:
https://github.com/standardhealth/shr_spec/commit/937f31c8091cff6a3ec33bbc90a77ebb15c5944f

I'm assuming that means this issue can be closed, but would like @markkramerus to confirm.

**Comment by rutemartins** [comment]
I can confirm - he did it while I was watching!
