### ISSUE TITLE
Members vs. evaluation components

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/ballot#44]
Members seems to be a mandatory attribute for BreastCancerHistologicGrade (but it could apply to other data elements). It seems to be a CIMI construct, but while it's mandatory it is not constrained and doesn't actually contain any individual observations. These are defined under EvaluationComponent. Can we get rid of the members attribute for models that don't use it?

**Comment by markkramerus** [comment]
Changed Members to 0..1
