### ISSUE TITLE
Replace "HL7 Cancer Interoperability" Group with "Cancer Interoperability Group" in auto-generated publication note

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/ballot#45]
The sentence appears on every logical model and profile page.

**Comment by markkramerus** [comment]
very minor. I actually think HL7 is appropriate.

**Comment by cmoesel** [comment]
This comes from `config.json`'s `publisher` field, just like in #34.  I've been avoiding changes to shr_spec (don't want too many cooks in the kitchen) -- so re-assigning to Mark and Rute.

**Comment by markkramerus** [comment]
I'm sticking with HL7.
