### ISSUE TITLE
Bad Value Set URL

### ISSUE THREAD

**Issue by cmoesel** [standardhealth/ballot#48]
`ConditionTopic` has this:
```
1..*	Category should be from http://hl7.org/fhir/us/core/CodeSystem/condition-category
```

That URL points to a Code System _not_ a Value Set.  It needs to point to a Value Set.

See: https://github.com/standardhealth/shr_spec/blob/may-2018-ballot-topic-context/spec/cimi.txt#L306

**Comment by rutemartins** [comment]
The correct URL is http://hl7.org/fhir/us/core/ValueSet-us-core-condition-category.html

**Comment by cmoesel** [comment]
Well... not exactly.  You have to use the "defining" URL of the value set.  If you click the link @rutemartins provided, you'll see the defining URL specified there as http://hl7.org/fhir/us/core/ValueSet/us-core-condition-category.

So the fix needs to be:
```
1..* Category should be from http://hl7.org/fhir/us/core/ValueSet/us-core-condition-category
```

**Comment by markkramerus** [comment]
fixed
