### ISSUE TITLE
Wrong code for M Category

### ISSUE THREAD

**Issue by cmoesel** [standardhealth/ballot#50]
Currently, we have this definition:
```
Element:  BreastCancerDistantMetastasesClassification
Concept:  SCT#126926005 "M category"	//RMB: was LNC#59522-3, which is specific to AJCC 7th edition
```

But `SCT#126926005` is really the code for `Neoplasm of the breast`.

I believe the correct code is `SCT#277208005` (M category).

**Comment by markkramerus** [comment]
fixed & committed
