### ISSUE TITLE
Missing code for BreastCancerStage.EvaluationResultTopic.Value?

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/ballot#52]
BreastCancerStage.EvaluationResultTopic.TopicCode is set to "malignant neoplasm of breast staging", which I *think* is the CIMI "answer". However BreastCancerStage.EvaluationResultTopic is just contrained to be CodeableConcept. Should we include a code? I'm at a loss for what it should be, although I suspect some sort of "question"?

**Comment by markkramerus** [comment]
"malignant neoplasm of breast staging" is the question. EvaluationResultTopic value is the answer; it is the stage itself. It used to be the BreastCancerStageVS before the stripping of AJCC content.
