### ISSUE TITLE
Extraneous attributes for BreastCancerStage

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/ballot#53]
Seems like there are some extraneous attributes for BreastCancerStage.EvaluationResultTopic. Suggest additional constraints:

```
0..0			EvaluationResultTopic.AnatomicalLocation
0..0			EvaluationResultTopic.Specimen
0..0			EvaluationResultTopic.ReferenceRange
```

The stage group is assigned based on a wealth of information, which usually won't be constrained to a single anatomical location (if the cancer is metastatic) or specimen, since it may derive from clinical findings only. Doesn't seem very plausible this information would be associated with the stage group.

If change is made, will need to change the description of the data element in CIMPL, since it references the cardinality of some of these attributes.

**Comment by markkramerus** [comment]
Not sure what you mean by changing the description of the data element. Looks ok to me.

**Comment by markkramerus** [comment]
(I did put the 0..0 element as suggested)

**Comment by rutemartins** [comment]
The data element description has some notes about CIMI alignment that refer to these attributes, which will no longer be there
