### ISSUE TITLE
Should HER2byIHC.EvaluationResultTopic.FindingMethod be a fixed code?

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/ballot#55]
Right now we refer to a single code value set:
```
EvaluationResultTopic.FindingMethod from HER2IHCMethodVS
```
Suggest:
```
EvaluationResultTopic.FindingMethod is #ihc "HER2 by ImmunoHistochemistry"
```

**Comment by markkramerus** [comment]
Can't do that because the code system is required - but since it is a local code, the code system doesn't exist until after the IG is run. Have to leave it as-is.
