### ISSUE TITLE
HER2ReceptorStatus and DiagnosticService

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/ballot#56]
On `HER2ReceptorStatus`, `DiagnosticService` is set to `pathology`. The attribute exists but is not set for `HER21ReceptorStatus` members.

If we want it to be at the `HER2ReceptorStatus` level, should we zero the attribute out in the members? Conversely, should `DiagnosticService` only be assigned at the members level, since those are labs vs. evaluation results?

**Comment by markkramerus** [comment]
Members are independent, self-contained, complete observations, so the DiagnosticService should be set on each HER test. Added DiagnosticService to the 2 HER2 classes
