### ISSUE TITLE
Terminology binding names are all set to "?ext"

### ISSUE THREAD

**Issue by okeefm** [standardhealth/ballot#6]
In the IG, all the Terminology Binding `name` fields are set to `?ext`, not the actual name of the binding.

<img width="715" alt="screen shot 2018-03-19 at 3 59 11 pm" src="https://user-images.githubusercontent.com/49001/37619394-c0cf35cc-2b8f-11e8-836f-4acb94222acf.png">

Example IG link: https://cdn.rawgit.com/standardhealth/ballot/expanded/site/StructureDefinition-oncology-BreastCancer.html

A similar link from the StandardHealthRecord.org version of the IG, that only exhibits this behavior for one of the bindings: http://standardhealthrecord.org/fhir/StructureDefinition-shr-oncology-BreastCancer.html

**Comment by cmoesel** [comment]
I'm not sure what these are exactly -- but I wonder if the name is intended to be resolved via the terminology service?  This will require some further investigation.  The fact that it works on the SHR.org one might indicate it is a difference introduced by the 3.2 publisher (the SHR.org one uses the 3.0.1 publisher).

**Comment by okeefm** [comment]
Also, the Terminology Binding links in the Differential Table actually link to the definitions in the GitHub repos, but the ones in this table link to the link displayed (the hl7.org one), so they don't resolve.

**Comment by cmoesel** [comment]
This is fixed in the latest builds of the IG publisher.
