### ISSUE TITLE
Logical Model types show up as unlinked URLs in the snapshot table

### ISSUE THREAD

**Issue by cmoesel** [standardhealth/ballot#61]
Due to a bug/limitation in the FHIR IG publisher, logical model snapshot tables use long, unlinked URIs.

![image](https://user-images.githubusercontent.com/2278253/38069092-9060cbe4-32e2-11e8-8b0f-547b216909d4.png)

**Comment by cmoesel** [comment]
Fixed locally via post-processing of the Jekyll includes and tons of string matching.  Not a pretty solution, but certainly a pretty outcome.

![image](https://user-images.githubusercontent.com/2278253/38069156-e71fde48-32e2-11e8-8316-bb6572a429b3.png)

**Comment by markkramerus** [comment]
much better

**Comment by cmoesel** [comment]
Deployed.
