### ISSUE TITLE
One more Pull Request with copy edits

### ISSUE THREAD

**Issue by okeefm** [standardhealth/ballot#63]
A final batch of copy edits, this time to `breastCancerIndexContent.html`, which I didn't get a chance to look at last time.

@cmoesel I removed the paragraph regarding the property type URLs in logical models, because I'm pretty sure that's been fixed. If that's not correct, let me know.

**Comment by cmoesel** [comment]
https://github.com/standardhealth/shr_spec/pull/83

**Comment by okeefm** [comment]
Thanks. Meant to link this, but apparently got distracted.

**Comment by markkramerus** [comment]
done
