### ISSUE TITLE
Upside down class hierarchy in MoraDoc

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/ballot#8]
Locatable is the top level class. The class tree is backwards.

![capture](https://user-images.githubusercontent.com/492232/37788175-25225c90-2dd7-11e8-941e-967539df3ed3.JPG)

**Comment by Abhijay** [comment]
Oh hmm... I'll have to see what's going on there.

After a quick look: It doesn't to be happening to all elements, only certain cases. I'll investigate

**Comment by Abhijay** [comment]
It is resolved in the latest build of the logical_models cli.

(However, the IGPublisher is currently broken (tx.fhir.org is down), so we can't push the new IG out until that is fixed)

**Comment by Abhijay** [comment]
Update: is now resolved in latest build

http://build.fhir.org/ig/HL7/us-breastcancer/modeldoc/index.html
