### ISSUE TITLE
Menu Bar Simple Fix

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/ballot#9]
Can you move the "Launch Model Browser" link to the far right, and re-name it "Reference Model"?
![capture](https://user-images.githubusercontent.com/492232/37789955-9d4522e4-2ddb-11e8-8410-3abfeb772ed6.JPG)

**Comment by cmoesel** [comment]
Yes

**Comment by cmoesel** [comment]
@markkramerus - Depending on what you mean by "far right" this is either fixed or not.  It's the right-most item in the menu now -- but it's not aligned-right on the screen if that's what you meant.  Is this good enough?
![ig-menu](https://user-images.githubusercontent.com/2278253/37798952-a50f3c12-2df4-11e8-93cf-f7a3cc1718ad.png)

**Comment by markkramerus** [comment]
This is perfect. That's what I meant.
